server:
  tomcat:
    max-swallow-size: 10MB
    max-http-form-post-size: 10MB
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: mobile_api
  datasource:
    #配置数据库连接池种类
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qingqing?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    druid:
      initial-size: 5
      max-active: 100
      min-idle: 10
  data:
    redis:
      host: localhost
      port: 6379
      password: javasm
      database: 2
  task:
    execution:
      pool:
        core-size: 10
        max-size: 20
        queue-capacity: 1000
    scheduling:
      pool:
        size: 10
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl